ludus:
  - vm_name: "{{ range_id }}-BBI-HQ-DC"
    hostname: "{{ range_id }}-BBI-HQ-DC"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-HQ-SQL"
    hostname: "{{ range_id }}-BBI-HQ-SQL"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 20
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-HQ-SQUID"
    hostname: "{{ range_id }}-BBI-HQ-SQUID"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    linux: true
  - vm_name: "{{ range_id }}-BBI-HQ-SCCM"
    hostname: "{{ range_id }}-BBI-HQ-SCCM"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 40
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-HQ-ES"
    hostname: "{{ range_id }}-BBI-HQ-ES"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 250
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-CORP-DC"
    hostname: "{{ range_id }}-BBI-CORP-DC"
    template: win2019-server-x64-template
    vlan: 20
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-CORP-WKSTN1"
    hostname: "{{ range_id }}-BBI-CORP-WKSTN1"
    template: win11-22h2-x64-enterprise-template
    vlan: 20
    ip_last_octet: 20
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-CORP-WKSTN2"
    hostname: "{{ range_id }}-BBI-CORP-WKSTN2"
    template: win11-22h2-x64-enterprise-template
    vlan: 20
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-RD-DC"
    hostname: "{{ range_id }}-BBI-RD-DC"
    template: win2019-server-x64-template
    vlan: 30
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-RD-SQL"
    hostname: "{{ range_id }}-BBI-RD-SQL"
    template: win2019-server-x64-template
    vlan: 30
    ip_last_octet: 20
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-RD-WKSTN1"
    hostname: "{{ range_id }}-BBI-RD-WKSTN1"
    template: win11-22h2-x64-enterprise-template
    vlan: 30
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-SW-DC"
    hostname: "{{ range_id }}-BBI-SW-DC"
    template: win2019-server-x64-template
    vlan: 40
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-SW-WKSTN1"
    hostname: "{{ range_id }}-BBI-SW-WKSTN1"
    template: win11-22h2-x64-enterprise-template
    vlan: 40
    ip_last_octet: 20
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-SW-FS"
    hostname: "{{ range_id }}-BBI-SW-FS"
    template: win2019-server-x64-template
    vlan: 40
    ip_last_octet: 30
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-BBI-DMZ-DC"
    hostname: "{{ range_id }}-BBI-DMZ-DC"
    template: win2019-server-x64-template
    vlan: 100
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    roles:
      - ludus_foreign_domain
    role_vars:
      create_dns_delegation: true
      new_domain_name: "dmz.dmz"
      new_domain_netbios_name: "dmz"
      domain_mode: "WinThreshold"
      forest_mode: "WinThreshold"
      reboot: true
      SafeModeAdministratorPassword: "Password123!"
  - vm_name: "{{ range_id }}-BBI-DMZ-WEB"
    hostname: "{{ range_id }}-BBI-DMZ-WEB"
    template: debian-12-x64-server-template
    vlan: 100
    ip_last_octet: 20
    ram_gb: 4
    cpus: 2
    linux: true
  - vm_name: "{{ range_id }}-kali"
    hostname: "{{ range_id }}-kali"
    template: kali-x64-desktop-template
    vlan: 200
    ip_last_octet: 100
    ram_gb: 8
    cpus: 4
    linux: true
    testing:
      snapshot: false
      block_internet: false
  - vm_name: "{{ range_id }}-attacker"
    hostname: "{{ range_id }}-attacker"
    template: win11-22h2-x64-enterprise-template
    vlan: 200
    ip_last_octet: 101
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
network:
  external_default: REJECT
  inter_vlan_default: REJECT
  rules:
    - name: Allow VLAN 200 out to internet
      vlan_src: 200
      vlan_dst: public
      protocol: all
      ports: all
      action: ACCEPT
    - name: Only allow TCP 80 from VLAN 200 to VLAN 100
      vlan_src: 200
      vlan_dst: 100
      protocol: tcp
      ports: 80
      action: ACCEPT
    - name: Only allow TCP 443 from VLAN 200 to VLAN 100
      vlan_src: 200
      vlan_dst: 100
      protocol: tcp
      ports: 443
      action: ACCEPT
    - name: Allow all traffic from VLAN 100 to VLAN 200(simulated internet)
      vlan_src: 100
      vlan_dst: 200
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow SQUID access to VLAN 200(simulated internet)
      vlan_src: 10
      ip_last_octet_src: 30
      vlan_dst: 200
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow HQ (10) to CORP (20)
      vlan_src: 10
      vlan_dst: 20
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow CORP (20) to HQ (10)
      vlan_src: 20
      vlan_dst: 10
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow HQ (10) to R&D (30)
      vlan_src: 10
      vlan_dst: 30
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow R&D (30) to HQ (10)
      vlan_src: 30
      vlan_dst: 10
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow CORP (20) to R&D (30)
      vlan_src: 20
      vlan_dst: 30
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow R&D (30) to CORP (20)
      vlan_src: 30
      vlan_dst: 20
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow DMZ DC to CORP DC
      vlan_src: 100
      ip_last_octet_src: 10
      vlan_dst: 20
      ip_last_octet_dst: 10
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow CORP DC to DMZ DC
      vlan_src: 20
      ip_last_octet_src: 10
      vlan_dst: 100
      ip_last_octet_dst: 10
      protocol: all
      ports: all
      action: ACCEPT